# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 44042a7f0f8a8ec2123c543b5c40234109d69db5bd178f87d4bf649c22d57bf7a71d78889a7728ff1d4043e99b62acb3e96d83ef7ec8043f7bfc62c5bc399f77

test:
  secret_key_base: 464c2c9048ff9d9639772afffe4b1d286e116092937f6c852efa90ba6385cf33e3697f4b6fb26939a63d0362fbd60986037505f6850bab01cc63993c0a223f5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
